import type { ProductLine } from '@secondshelf/engine';

/**
 * The twenty four fresh lines the prototype trades. Prices and costs are whole
 * pence and weights whole grams, so no figure downstream ever needs a float.
 * Stock, velocity, life and sensitivity are the typical weekday values for a
 * single large store.
 */
export const CATALOGUE: readonly ProductLine[] = Object.freeze([
  Object.freeze({
    id: 'bagged-rocket-80g',
    name: 'Bagged Rocket, 80g',
    category: 'Produce',
    fullPricePence: 110,
    unitCostPence: 42,
    unitWeightGrams: 80,
    typicalDailyStock: 34,
    baselineUnitsPerHour: 1.5,
    saleableHoursAtOpen: 11,
    sensitivityMultiplier: 1.15,
  }),
  Object.freeze({
    id: 'british-chicken-thighs-1kg',
    name: 'British Chicken Thighs, 1kg',
    category: 'Meat',
    fullPricePence: 425,
    unitCostPence: 260,
    unitWeightGrams: 1000,
    typicalDailyStock: 26,
    baselineUnitsPerHour: 1.3,
    saleableHoursAtOpen: 9,
    sensitivityMultiplier: 1.05,
  }),
  Object.freeze({
    id: 'strawberries-400g',
    name: 'Strawberries, 400g',
    category: 'Produce',
    fullPricePence: 275,
    unitCostPence: 130,
    unitWeightGrams: 400,
    typicalDailyStock: 40,
    baselineUnitsPerHour: 2.1,
    saleableHoursAtOpen: 10,
    sensitivityMultiplier: 1.2,
  }),
  Object.freeze({
    id: 'whole-milk-2l',
    name: 'Whole Milk, 2L',
    category: 'Dairy',
    fullPricePence: 145,
    unitCostPence: 95,
    unitWeightGrams: 2060,
    typicalDailyStock: 58,
    baselineUnitsPerHour: 3.4,
    saleableHoursAtOpen: 14,
    sensitivityMultiplier: 0.7,
  }),
  Object.freeze({
    id: 'sourdough-loaf-800g',
    name: 'Sourdough Loaf, 800g',
    category: 'Bakery',
    fullPricePence: 240,
    unitCostPence: 85,
    unitWeightGrams: 800,
    typicalDailyStock: 22,
    baselineUnitsPerHour: 1.4,
    saleableHoursAtOpen: 13,
    sensitivityMultiplier: 0.95,
  }),
  Object.freeze({
    id: 'scottish-salmon-fillets-240g',
    name: 'Scottish Salmon Fillets, 240g',
    category: 'Fish',
    fullPricePence: 550,
    unitCostPence: 340,
    unitWeightGrams: 240,
    typicalDailyStock: 18,
    baselineUnitsPerHour: 0.9,
    saleableHoursAtOpen: 8,
    sensitivityMultiplier: 1,
  }),
  Object.freeze({
    id: 'beef-mince-5-500g',
    name: 'Beef Mince 5%, 500g',
    category: 'Meat',
    fullPricePence: 400,
    unitCostPence: 255,
    unitWeightGrams: 500,
    typicalDailyStock: 30,
    baselineUnitsPerHour: 1.6,
    saleableHoursAtOpen: 10,
    sensitivityMultiplier: 1,
  }),
  Object.freeze({
    id: 'chicken-caesar-wrap',
    name: 'Chicken Caesar Wrap',
    category: 'Food to go',
    fullPricePence: 350,
    unitCostPence: 115,
    unitWeightGrams: 220,
    typicalDailyStock: 44,
    baselineUnitsPerHour: 2.6,
    saleableHoursAtOpen: 7,
    sensitivityMultiplier: 1.45,
  }),
  Object.freeze({
    id: 'houmous-200g',
    name: 'Houmous, 200g',
    category: 'Chilled',
    fullPricePence: 130,
    unitCostPence: 55,
    unitWeightGrams: 200,
    typicalDailyStock: 36,
    baselineUnitsPerHour: 1.7,
    saleableHoursAtOpen: 12,
    sensitivityMultiplier: 1.05,
  }),
  Object.freeze({
    id: 'raspberries-150g',
    name: 'Raspberries, 150g',
    category: 'Produce',
    fullPricePence: 250,
    unitCostPence: 135,
    unitWeightGrams: 150,
    typicalDailyStock: 28,
    baselineUnitsPerHour: 1.4,
    saleableHoursAtOpen: 8,
    sensitivityMultiplier: 1.25,
  }),
  Object.freeze({
    id: 'fresh-egg-tagliatelle-300g',
    name: 'Fresh Egg Tagliatelle, 300g',
    category: 'Chilled',
    fullPricePence: 220,
    unitCostPence: 95,
    unitWeightGrams: 300,
    typicalDailyStock: 24,
    baselineUnitsPerHour: 1.1,
    saleableHoursAtOpen: 13,
    sensitivityMultiplier: 0.95,
  }),
  Object.freeze({
    id: 'cooked-king-prawns-180g',
    name: 'Cooked King Prawns, 180g',
    category: 'Fish',
    fullPricePence: 475,
    unitCostPence: 290,
    unitWeightGrams: 180,
    typicalDailyStock: 16,
    baselineUnitsPerHour: 0.8,
    saleableHoursAtOpen: 9,
    sensitivityMultiplier: 1.05,
  }),
  Object.freeze({
    id: 'coleslaw-300g',
    name: 'Coleslaw, 300g',
    category: 'Chilled',
    fullPricePence: 120,
    unitCostPence: 48,
    unitWeightGrams: 300,
    typicalDailyStock: 30,
    baselineUnitsPerHour: 1.5,
    saleableHoursAtOpen: 12,
    sensitivityMultiplier: 0.9,
  }),
  Object.freeze({
    id: 'blueberries-200g',
    name: 'Blueberries, 200g',
    category: 'Produce',
    fullPricePence: 290,
    unitCostPence: 155,
    unitWeightGrams: 200,
    typicalDailyStock: 26,
    baselineUnitsPerHour: 1.3,
    saleableHoursAtOpen: 9,
    sensitivityMultiplier: 1.2,
  }),
  Object.freeze({
    id: 'cumberland-sausages-400g',
    name: 'Cumberland Sausages, 400g',
    category: 'Meat',
    fullPricePence: 310,
    unitCostPence: 175,
    unitWeightGrams: 400,
    typicalDailyStock: 28,
    baselineUnitsPerHour: 1.4,
    saleableHoursAtOpen: 11,
    sensitivityMultiplier: 0.95,
  }),
  Object.freeze({
    id: 'egg-and-cress-sandwich',
    name: 'Egg and Cress Sandwich',
    category: 'Food to go',
    fullPricePence: 260,
    unitCostPence: 80,
    unitWeightGrams: 190,
    typicalDailyStock: 50,
    baselineUnitsPerHour: 3,
    saleableHoursAtOpen: 7,
    sensitivityMultiplier: 1.5,
  }),
  Object.freeze({
    id: 'greek-style-yoghurt-500g',
    name: 'Greek Style Yoghurt, 500g',
    category: 'Dairy',
    fullPricePence: 175,
    unitCostPence: 80,
    unitWeightGrams: 500,
    typicalDailyStock: 32,
    baselineUnitsPerHour: 1.5,
    saleableHoursAtOpen: 13,
    sensitivityMultiplier: 0.8,
  }),
  Object.freeze({
    id: 'baby-spinach-200g',
    name: 'Baby Spinach, 200g',
    category: 'Produce',
    fullPricePence: 160,
    unitCostPence: 65,
    unitWeightGrams: 200,
    typicalDailyStock: 30,
    baselineUnitsPerHour: 1.4,
    saleableHoursAtOpen: 10,
    sensitivityMultiplier: 1.15,
  }),
  Object.freeze({
    id: 'cod-fillets-260g',
    name: 'Cod Fillets, 260g',
    category: 'Fish',
    fullPricePence: 490,
    unitCostPence: 305,
    unitWeightGrams: 260,
    typicalDailyStock: 14,
    baselineUnitsPerHour: 0.7,
    saleableHoursAtOpen: 8,
    sensitivityMultiplier: 1,
  }),
  Object.freeze({
    id: 'rotisserie-chicken-whole',
    name: 'Rotisserie Chicken, whole',
    category: 'Food to go',
    fullPricePence: 550,
    unitCostPence: 240,
    unitWeightGrams: 1300,
    typicalDailyStock: 20,
    baselineUnitsPerHour: 1.2,
    saleableHoursAtOpen: 6,
    sensitivityMultiplier: 1.35,
  }),
  Object.freeze({
    id: 'vine-tomatoes-400g',
    name: 'Vine Tomatoes, 400g',
    category: 'Produce',
    fullPricePence: 185,
    unitCostPence: 80,
    unitWeightGrams: 400,
    typicalDailyStock: 34,
    baselineUnitsPerHour: 1.6,
    saleableHoursAtOpen: 11,
    sensitivityMultiplier: 1.1,
  }),
  Object.freeze({
    id: 'fresh-orange-juice-1l',
    name: 'Fresh Orange Juice, 1L',
    category: 'Chilled',
    fullPricePence: 230,
    unitCostPence: 110,
    unitWeightGrams: 1030,
    typicalDailyStock: 26,
    baselineUnitsPerHour: 1.2,
    saleableHoursAtOpen: 13,
    sensitivityMultiplier: 0.85,
  }),
  Object.freeze({
    id: 'chicken-kyiv-2-pack',
    name: 'Chicken Kyiv, 2 pack',
    category: 'Chilled',
    fullPricePence: 340,
    unitCostPence: 180,
    unitWeightGrams: 360,
    typicalDailyStock: 22,
    baselineUnitsPerHour: 1.1,
    saleableHoursAtOpen: 12,
    sensitivityMultiplier: 0.95,
  }),
  Object.freeze({
    id: 'pain-au-chocolat-4-pack',
    name: 'Pain au Chocolat, 4 pack',
    category: 'Bakery',
    fullPricePence: 190,
    unitCostPence: 60,
    unitWeightGrams: 280,
    typicalDailyStock: 26,
    baselineUnitsPerHour: 1.3,
    saleableHoursAtOpen: 13,
    sensitivityMultiplier: 1,
  }),
] satisfies readonly ProductLine[]);
